# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "17374faebae54e5f6ded894878b9c293"
application_url = "https://confidence-quick-quotes-joyce.trycloudflare.com"
embedded = true
name = "3D-tryon"
handle = "3d-tryon"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://confidence-quick-quotes-joyce.trycloudflare.com/auth/callback",
  "https://confidence-quick-quotes-joyce.trycloudflare.com/auth/shopify/callback",
  "https://confidence-quick-quotes-joyce.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "simflection.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
